### 학번 : 19615049       이름 : 최명헌 

In [1]:
1+1

2

In [2]:
5-2

3

In [3]:
2*3

6

In [4]:
2**3

8

In [5]:
6/3

2.0

In [6]:
7//3

2

In [7]:
"A"

'A'

In [8]:
'A'

'A'

In [9]:
type("A")

str

In [10]:
type('A')

str

In [11]:
type(1)

int

In [12]:
type(2.4)

float

In [13]:
type(True)

bool

In [14]:
type(False)

bool

In [15]:
"A"+1
#str과 int형 간의 연산이 불가함

TypeError: can only concatenate str (not "int") to str

In [16]:
1>0.89

True

In [17]:
3>=2

True

In [18]:
3<2

False

In [19]:
3<=2

False

In [20]:
3==2

False

In [21]:
3!=2

True

In [22]:
x=2
x+1

3

In [23]:
(x+2)*4

16

In [24]:
def sample_function(data):
    return ((data+2)*4)

In [25]:
sample_function(x)

16

In [26]:
sample_function(3)

20

In [27]:
sample_function(x) + sample_function(3)

36

In [28]:
class Sample_Class:
    def __init__(self,data1,data2):
        self.data1 = data1
        self.data2 = data2
        
    def method2(self):
        return (self.data1 + self.data2)

In [29]:
sample_instance = Sample_Class(data1=2,data2=3)

In [30]:
sample_instance.data1

2

In [31]:
sample_instance.method2()

5

In [32]:
data = 1
if data<2:
    print("2보다 작은 데이터입니다.")
else:
    print("2이상인 데이터입니다.")

2보다 작은 데이터입니다.


In [33]:
data = 3
if data<2:
    print("2보다 작은 데이터입니다.")
else:
    print("2이상인 데이터입니다.")

2이상인 데이터입니다.


In [34]:
import numpy as np

In [35]:
import pandas as pd

In [36]:
sample_list = [1,2,3,4,5]
sample_list

[1, 2, 3, 4, 5]

In [37]:
sample_array = np.array([1,2,3,4,5])
sample_array

array([1, 2, 3, 4, 5])

In [38]:
sample_array+2

array([3, 4, 5, 6, 7])

In [39]:
np.array([1,2,"A"])

array(['1', '2', 'A'], dtype='<U21')

In [40]:
sample_array_2 = np.array([[1,2,3,4,5],
                          [6,7,8,9,10]])
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
sample_array_2.shape

(2, 5)

In [42]:
np.arange(start=1,stop=6,step=1)

array([1, 2, 3, 4, 5])

In [43]:
np.arange(start=0.1,stop=0.8,step=0.2)

array([0.1, 0.3, 0.5, 0.7])

In [44]:
np.arange(0.1,0.8,0.2)

array([0.1, 0.3, 0.5, 0.7])

In [45]:
np.tile("A",5)

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [46]:
np.tile(0,4)

array([0, 0, 0, 0])

In [47]:
np.zeros(4)

array([0., 0., 0., 0.])

In [48]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones(3)

array([1., 1., 1.])

In [50]:
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [51]:
d1_array[0]

1

In [52]:
d1_array[1:3]

array([2, 3])

In [53]:
d2_array = np.array([[1,2,3,4,5],
                          [6,7,8,9,10]])
d2_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
d2_array[0,3]

4

In [55]:
d2_array[1,2:4]

array([8, 9])

In [56]:
sample_df = pd.DataFrame({
    'col1' : sample_array,
    'col2' : sample_array*2,
    'col3' : ["A","B","C","D","E"]
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [57]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [58]:
file_data = pd.read_csv("/Users/choemyeongheon/Desktop/desa/2-4-1-sample_data.csv")
print(file_data)

   Col1 Col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [59]:
type(file_data)

pandas.core.frame.DataFrame

In [60]:
df_1 = pd.DataFrame({
    'col1' : np.array([1,2,3]),
    'col2' : np.array(["A","B","C"])
})
df_2 = pd.DataFrame({
    'col1' : np.array([4,5,6]),
    'col2' : np.array(["D","E","F"])
})

In [61]:
print(pd.concat([df_1,df_2]))

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [62]:
print(pd.concat([df_1,df_2], axis=1))

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F


In [63]:
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [64]:
print(sample_df.col2)

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64


In [65]:
print(sample_df["col2"])

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64


In [66]:
print(sample_df[["col2","col3"]])

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [67]:
print(sample_df.drop("col1",axis=1))

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [68]:
print(sample_df.head(n=3))

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C


In [69]:
print(sample_df.query('index==0'))

   col1  col2 col3
0     1     2    A


In [70]:
print(sample_df.query('col3=="A" | col3=="D"'))

   col1  col2 col3
0     1     2    A
3     4     8    D


In [71]:
print(sample_df.query('col3=="A" & col1==3'))

Empty DataFrame
Columns: [col1, col2, col3]
Index: []


In [72]:
print(sample_df.query('col3=="A"')[["col2","col3"]])

   col2 col3
0     2    A


In [73]:
type(sample_df)

pandas.core.frame.DataFrame

In [74]:
type(sample_df.col1)

pandas.core.series.Series

In [75]:
type(np.array(sample_df.col1))

numpy.ndarray

In [76]:
type(sample_df.col1.values)

numpy.ndarray

In [77]:
help(sample_df.query)

Help on method query in module pandas.core.frame:

query(expr: 'str', inplace: 'bool' = False, **kwargs) method of pandas.core.frame.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.
    
    Parameters
    ----------
    expr : str
        The query string to evaluate.
    
        You can refer to variables
        in the environment by prefixing them with an '@' character like
        ``@a + b``.
    
        You can refer to column names that are not valid Python variable names
        by surrounding them in backticks. Thus, column names containing spaces
        or punctuations (besides underscores) or starting with digits must be
        surrounded by backticks. (For example, a column named "Area (cm^2)" would
        be referenced as ```Area (cm^2)```). Column names which are Python keywords
        (like "list", "for", "import", etc) cannot be used.
    
        For example, if one of your columns is called ``a a`` and you want
        to sum it